language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mv ../cakephp-codesniffer ../CakePHP && cd ../CakePHP
  - composer selfupdate
  - composer install

script:
  - phpunit

notifications:
  email: false
