language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mv ../cakephp-codesniffer ../cakephp_codesniffer && cd ../cakephp_codesniffer
  - composer selfupdate
  - composer install

script:
  - cd CakePHP && phpunit

notifications:
  email: false
